#include "PluginProcessor.h"
#include "PluginEditor.h"
#include "BinaryData.h"  // generated by juce_add_binary_data (HtmlToVst_UI target)

//==============================================================================

HtmlToVstAudioProcessorEditor::HtmlToVstAudioProcessorEditor (HtmlToVstAudioProcessor& p)
    : juce::AudioProcessorEditor (&p),
      processor (p),
      webView (juce::WebBrowserComponent::Options{})
{
    // Set plugin window size (adjust if needed)
    setSize (1100, 650);

    // 1) Get the embedded HTML from BinaryData (Assets/UI/ampex_ui.html)
    htmlData = juce::String::fromUTF8 (BinaryData::ampex_ui_html,
                                       BinaryData::ampex_ui_htmlSize);

    // 2) Turn it into a data: URL so WebBrowserComponent doesn’t need disk or network
    const juce::String encoded = juce::URL::addEscapeChars (htmlData, true);
    const juce::String dataUrl = "data:text/html," + encoded;

    // 3) Show the webview
    addAndMakeVisible (webView);

    // 4) Load the HTML directly from the data URL (no file://, no http://)
    webView.goToURL (dataUrl);
}

HtmlToVstAudioProcessorEditor::~HtmlToVstAudioProcessorEditor() = default;

//==============================================================================

void HtmlToVstAudioProcessorEditor::paint (juce::Graphics& g)
{
    g.fillAll (juce::Colours::black);
}

void HtmlToVstAudioProcessorEditor::resized()
{
    webView.setBounds (getLocalBounds());
}
