#include "PluginEditor.h"
#include "PluginProcessor.h"

// BinaryData for the HTML UI is generated by the HtmlUIData target
// into juce_binarydata_HtmlUIData/JuceLibraryCode/BinaryData.h
#include "BinaryData.h"

using namespace juce;

//==============================================================================

HtmlToVstPluginAudioProcessorEditor::HtmlToVstPluginAudioProcessorEditor (HtmlToVstPluginAudioProcessor& p)
    : AudioProcessorEditor (&p),
      audioProcessor (p)
{
    // Set an initial size for the plugin window
    setSize (1280, 720);

   #if JUCE_MAC
    // Avoid weird black backgrounds on macOS
    webView.setOpaque (false);
   #endif

    addAndMakeVisible (webView);

    // -----------------------------------------------------------------
    // 1) Grab the embedded HTML from BinaryData
    // -----------------------------------------------------------------
    const char* htmlData     = BinaryData::ampex_ui_html;
    const int   htmlDataSize = BinaryData::ampex_ui_htmlSize;

    String html (htmlData, htmlDataSize);

    // -----------------------------------------------------------------
    // 2) Encode as a data: URL so WebBrowserComponent treats it as HTML
    // -----------------------------------------------------------------
    // Escape characters so it’s safe to embed in a data: URL
    String encoded = URL::addEscapeChars (html, true, true, true);

    // Tell WebKit/WebView "this is HTML, not a normal URL"
    String dataUrl = "data:text/html;charset=utf-8," + encoded;

    // Load the HTML into the web view
    webView.goToURL (dataUrl);
}

//==============================================================================

HtmlToVstPluginAudioProcessorEditor::~HtmlToVstPluginAudioProcessorEditor()
{
}

void HtmlToVstPluginAudioProcessorEditor::paint (Graphics& g)
{
    // Fallback background (you probably won’t see this much since the HTML
    // covers the whole area, but it keeps things clean)
    g.fillAll (Colours::black);
}

void HtmlToVstPluginAudioProcessorEditor::resized()
{
    // Make the web view fill the entire editor area
    webView.setBounds (getLocalBounds());
}
