#include "PluginEditor.h"

// This header is generated by the HtmlUIData target.
// The include path is already present in your build logs.
#include "BinaryData.h"

using namespace juce;

static float parseFirstFloat (const String& s, float fallback = 0.0f)
{
    // extracts the first number from strings like "0.0 dB"
    for (int i = 0; i < s.length(); ++i)
    {
        if (CharacterFunctions::isDigit (s[i]) || s[i] == '-' || s[i] == '+')
        {
            auto tail = s.substring (i);
            auto v = tail.getFloatValue();
            if (std::isfinite (v))
                return v;
            break;
        }
    }
    return fallback;
}

HtmlToVstAudioProcessorEditor::HtmlToVstAudioProcessorEditor (HtmlToVstAudioProcessor& p)
    : AudioProcessorEditor (&p),
      processor (p),
      webView (*this)
{
    setOpaque (true);
    setSize (1100, 560);

    addAndMakeVisible (webView);

    tempDir = File::getSpecialLocation (File::tempDirectory)
                    .getChildFile ("HtmlToVstMachine");
    tempDir.createDirectory();

    tempHtmlFile = tempDir.getChildFile ("ui.html");

    loadUi();
    startTimerHz (30); // VU + UI polling speed
}

HtmlToVstAudioProcessorEditor::~HtmlToVstAudioProcessorEditor()
{
    stopTimer();
}

void HtmlToVstAudioProcessorEditor::paint (Graphics& g)
{
    g.fillAll (Colours::black);
}

void HtmlToVstAudioProcessorEditor::resized()
{
    webView.setBounds (getLocalBounds());
}

bool HtmlToVstAudioProcessorEditor::InterceptingWebView::pageAboutToLoad (const String& newURL)
{
    if (newURL.startsWithIgnoreCase ("juce://") || newURL.startsWithIgnoreCase ("juce:"))
    {
        editor.handleJuceUrl (newURL);
        return false; // stop actual navigation
    }
    return true;
}

static String injectBridgeScript (const String& html)
{
    // We don't assume anything about your UI internals other than:
    //  - #val-in, #val-out, #val-bias contain "X.X dB"
    //  - #transformer has class "active" when on
    //
    // We add a hidden iframe sender + polling loop.
    const String js = R"JS(
<script>
(function(){
  function q(id){ return document.getElementById(id); }
  function readDb(id){
    var el=q(id); if(!el) return null;
    var m = (el.textContent||"").match(/-?\d+(\.\d+)?/);
    return m ? parseFloat(m[0]) : 0;
  }
  function readToggle(id){
    var el=q(id); if(!el) return null;
    return el.classList.contains("active") ? 1 : 0;
  }
  function send(params){
    try{
      var i = q("__juce_ipc");
      if(!i){
        i = document.createElement("iframe");
        i.style.display="none";
        i.id="__juce_ipc";
        document.body.appendChild(i);
      }
      i.src = "juce://ui?" + params + "&t=" + Date.now();
    }catch(e){}
  }

  var last = {};
  function poll(){
    var inDb  = readDb("val-in");
    var outDb = readDb("val-out");
    var biasDb = readDb("val-bias");
    var xformer = readToggle("transformer");

    var payload = { inDb: inDb, outDb: outDb, biasDb: biasDb, transformer: xformer };
    var changed = false;

    Object.keys(payload).forEach(function(k){
      if(payload[k] === null || payload[k] === undefined) return;
      if(last[k] !== payload[k]) { last[k] = payload[k]; changed = true; }
    });

    if(!changed) return;

    var qs = Object.keys(payload)
      .filter(function(k){ return payload[k] !== null && payload[k] !== undefined; })
      .map(function(k){ return k + "=" + encodeURIComponent(payload[k]); })
      .join("&");

    send(qs);
  }

  setInterval(poll, 50);

  // also poll shortly after clicks (helps toggle switches)
  document.addEventListener("click", function(){ setTimeout(poll, 0); });

})();
</script>
)JS";

    // insert before </body> if possible, else append
    const auto lower = html.toLowerCase();
    const int bodyClose = lower.lastIndexOf ("</body>");
    if (bodyClose >= 0)
        return html.substring (0, bodyClose) + js + html.substring (bodyClose);

    return html + js;
}

String HtmlToVstAudioProcessorEditor::getEmbeddedHtmlOrFallback (String& debugInfoOut) const
{
    debugInfoOut.clear();

    // try to find any embedded *.html resource
    String chosen;

    for (int i = 0; i < BinaryData::namedResourceListSize; ++i)
    {
        if (auto* nm = BinaryData::namedResourceList[i])
        {
            const String name (nm);
            if (name.endsWithIgnoreCase ("_html") || name.endsWithIgnoreCase ("_htm"))
            {
                chosen = name;
                break;
            }
        }
    }

    if (chosen.isEmpty())
    {
        debugInfoOut = "BinaryData has no *_html resources.\n"
                       "Check that HtmlUIData is embedding your UI file.";
        return makeMissingUiHtml (debugInfoOut);
    }

    int sz = 0;
    if (auto* data = BinaryData::getNamedResource (chosen.toRawUTF8(), sz))
    {
        debugInfoOut = "Loaded embedded resource: " + chosen + " (" + String (sz) + " bytes)";
        const String htmlText = String::fromUTF8 ((const char*) data, sz);
        return injectBridgeScript (htmlText);
    }

    debugInfoOut = "Found candidate resource name but failed to load: " + chosen;
    return makeMissingUiHtml (debugInfoOut);
}

String HtmlToVstAudioProcessorEditor::makeMissingUiHtml (const String& extra)
{
    return String (R"HTML(
<!doctype html>
<html>
<head>
<meta charset="utf-8"/>
<meta name="viewport" content="width=device-width, initial-scale=1"/>
<title>UI Missing</title>
<style>
html,body{height:100%;margin:0;background:#0b1020;color:#e5e7eb;font-family:system-ui}
.wrap{height:100%;display:flex;align-items:center;justify-content:center;padding:16px}
.card{max-width:820px;width:100%;background:rgba(255,255,255,.06);border:1px solid rgba(255,255,255,.12);border-radius:14px;padding:16px}
code{white-space:pre-wrap;word-break:break-word;opacity:.9}
h2{margin:0 0 8px 0}
</style>
</head>
<body>
<div class="wrap">
  <div class="card">
    <h2>Embedded UI not found</h2>
    <p>The plugin built, but the embedded HTML resource wasn't found.</p>
    <code>)HTML")
    + extra
    + String (R"HTML(</code>
  </div>
</div>
</body>
</html>
)HTML");
}

void HtmlToVstAudioProcessorEditor::loadUi()
{
    String debug;
    auto html = getEmbeddedHtmlOrFallback (debug);

    // Write to a temp file then load with file://
    tempDir.createDirectory();
    tempHtmlFile.deleteFile();

    {
        FileOutputStream out (tempHtmlFile);
        out.setPosition (0);
        out.truncate();
        out.writeText (html, false, false, "\n");
        out.flush();
    }

    auto url = URL (tempHtmlFile).withParameter ("t", String (Time::getMillisecondCounter()));
    webView.goToURL (url.toString (true));
}

static String getQueryParam (const String& url, const String& key)
{
    // very small parser: looks after '?' and splits '&'
    const int q = url.indexOfChar ('?');
    if (q < 0) return {};
    auto qs = url.substring (q + 1);

    StringArray parts;
    parts.addTokens (qs, "&", "");
    for (auto& p : parts)
    {
        auto kv = StringArray::fromTokens (p, "=", "");
        if (kv.size() >= 2 && kv[0] == key)
            return URL::removeEscapeChars (kv[1]);
    }
    return {};
}

void HtmlToVstAudioProcessorEditor::handleJuceUrl (const String& urlString)
{
    // Expected format: juce://ui?inDb=...&outDb=...&biasDb=...&transformer=...
    if (! (urlString.containsIgnoreCase ("ui?") || urlString.containsIgnoreCase ("ui&") || urlString.containsIgnoreCase ("ui")))
        return;

    const float inDb  = parseFirstFloat (getQueryParam (urlString, "inDb"), 0.0f);
    const float outDb = parseFirstFloat (getQueryParam (urlString, "outDb"), 0.0f);
    const float biasDb = parseFirstFloat (getQueryParam (urlString, "biasDb"), 0.0f);

    const String x = getQueryParam (urlString, "transformer");
    const bool transformerOn = (x.isNotEmpty() ? (x.getIntValue() != 0) : true);

    processor.setUiParameters (inDb, outDb, biasDb, transformerOn);
}

void HtmlToVstAudioProcessorEditor::timerCallback()
{
    // Push VU values into the web UI
    const float lDb = processor.getCurrentVUL();
    const float rDb = processor.getCurrentVUR();

    const float lLin = Decibels::decibelsToGain (lDb, -100.0f);
    const float rLin = Decibels::decibelsToGain (rDb, -100.0f);

    const String js = "window.setVUMeters && window.setVUMeters("
                    + String (lLin, 6) + ","
                    + String (rLin, 6) + ");";

    webView.evaluateJavascript (js);
}
